import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MemeGeneratorHeader } from "@/components/meme-generator-header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MEME GENERATOR",
  description: "Generated by A Meme Generator",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <MemeGeneratorHeader />
        </header>
        {children}
      </body>
    </html>
  );
}
